# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.School'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('school',)]),
        ),
    ]
